# Strings and Tuples are immutable whereas Lists are mutable,
tup = ()
print(tup)
print(type(tup))
tup = (1)
print(tup)
print(type(tup))
tup = (2)
print(tup)
print(type(tup))
tup = (1,)
print(tup)
print(type(tup))
tup = (1,2,3,4,5,6,)
print(tup)
print(type(tup))
tup = (1,2,3,4,5,6)
print(tup)
print(type(tup))
# Tuple Slicing, similar to lists and strings,
print(tup[0:5])
print(tup[:len(tup)])
print(tup[0:])
print(tup[-5:-1])
print(tup.index(5))
tup = (1,2,3,1,3,5,3)
print(tup.count(3))
